[project]
name = "odoo-addons-oca-stock-logistics-availability"
version = "18.0.20250212.0"
dependencies = [
    "odoo-addon-stock_free_quantity==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
